#!/usr/bin/env node
/* Renders the social/meta images from the committed logo + data, so they can be
 * regenerated by anyone hosting a copy (URL and club count are read, not typed):
 *   og-image.png          1200×630  Open Graph / Twitter card
 *   favicon.png            64×64    PNG fallback for the SVG favicon
 *   apple-touch-icon.png  180×180   iOS home-screen icon
 * Run: `node scripts/og-image.mjs` (needs the Playwright dev dependency). */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "@playwright/test";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(readFileSync(`${ROOT}/package.json`, "utf8"));
const site = (pkg.homepage || "").replace(/^https?:\/\//, "").replace(/\/+$/, "");
let clubs = 0; try { clubs = (JSON.parse(readFileSync(`${ROOT}/data/latest.json`, "utf8")).clubs || []).length; } catch {}
const logo = readFileSync(`${ROOT}/logo.svg`, "utf8");
const favicon = readFileSync(`${ROOT}/favicon.svg`, "utf8");

const FONTS = `<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400..800&family=Space+Mono:wght@400;700&display=swap">`;
const og = `<!doctype html><meta charset="utf-8">${FONTS}<style>
  :root{--paper:#efece3;--ink:#0b0b0a;--accent:#ff3d00;--muted:#6b675d}
  body{margin:0;width:1200px;height:630px;background:var(--paper) radial-gradient(rgba(11,11,10,.14) 1px,transparent 1.5px) 0 0/22px 22px;font-family:"Bricolage Grotesque",sans-serif;color:var(--ink)}
  .f{position:absolute;inset:26px;border:2px solid var(--ink);padding:58px 86px;box-sizing:border-box}
  .top{display:flex;justify-content:space-between;align-items:center}
  .top svg{height:44px;width:auto;display:block}
  .tag{font-family:"Space Mono",monospace;font-weight:700;font-size:20px;letter-spacing:.08em;background:var(--accent);color:#fff;padding:8px 14px}
  .rule{height:2px;background:var(--ink);margin:26px 0 0}
  h1{margin:20px 0 0;font-size:82px;font-weight:800;letter-spacing:-.035em;line-height:.92}
  h1 span{color:var(--accent)}
  .lede{margin:20px 0 0;font-size:23px;color:var(--muted);max-width:52ch;line-height:1.3}
  .bot{position:absolute;left:86px;right:86px;bottom:56px;display:flex;justify-content:space-between;align-items:flex-end;border-top:2px solid var(--ink);padding-top:26px}
  .url{font-family:"Space Mono",monospace;font-weight:700;font-size:22px;color:var(--accent)}
  .meta{font-family:"Space Mono",monospace;font-size:17px;color:var(--muted);text-align:right;line-height:1.6}
  .meta b{color:var(--ink)}
</style><div class="f">
  <div class="top">${logo}<span class="tag">UNOFFICIAL</span></div>
  <div class="rule"></div>
  <h1>How much does<br>David Lloyd <span>cost?</span></h1>
  <p class="lede">Find what your local David Lloyd charges, compare plans and clubs, and see which tier your club sits in. No sign-up, no details needed.</p>
  <div class="bot"><div class="url">${site}</div><div class="meta">${clubs ? `<b>${clubs}</b> UK &amp; EU clubs<br>` : ""}real prices · no sign-up</div></div>
</div>`;

const icon = (size) => `<!doctype html><meta charset="utf-8"><style>body{margin:0;background:transparent}svg{display:block;width:${size}px;height:${size}px}</style>${favicon}`;

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1200, height: 630 } });
await page.setContent(og, { waitUntil: "networkidle" });
await page.evaluate(() => document.fonts.ready);
await page.screenshot({ path: `${ROOT}/og-image.png` });
for (const [file, size] of [["favicon.png", 64], ["apple-touch-icon.png", 180]]) {
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(icon(size));
  await page.screenshot({ path: `${ROOT}/${file}`, omitBackground: true });
}
await browser.close();
console.log(`Wrote og-image.png (${site}, ${clubs} clubs), favicon.png, apple-touch-icon.png`);
